alias vim='/c/Program\ Files/vim/vim74/vim.exe'
alias view='/c/Program\ Files/vim/vim74/vim.exe -R'
alias vimdiff='/c/Program\ Files/vim/vim74/vim.exe -d'
alias gvim='/c/Program\ Files/vim/vim74/gvim.exe -p --remote-tab-silent '
alias gvimdiff='/c/Program\ Files/vim/vim74/gvim.exe -p -d --remote-tab-silent '
